-- herdr-splits.nvim — seamless navigation/resizing across Herdr panes and
-- Neovim splits. Only loaded inside a Herdr pane (see the `enabled` guard in
-- nvim/plugin/lazy-load.lua); outside one the plain <C-w>h/j/k/l fallbacks in
-- user/keymaps.lua stay in charge.
--
-- setup() also WRITES the shared conf that the Herdr-side scripts read
-- (~/.config/herdr/plugins/config/herdr-splits/herdr-splits.conf), so the key
-- chords below must match the [[keys.command]] bindings generated by
-- modules/home-manager/programs/herdr.nix. Because the conf is what tells
-- Herdr which chords to forward, this must load eagerly (DeferredUIEnter) —
-- never lazily off the very keys it has to publish.

require("herdr-splits").setup({
	default_amount = 0.03, -- Herdr resize ratio
	neovim_amount = 3, -- Neovim resize cells
	at_edge = "wrap", -- Neovim window edge: continue on the opposite side
	nav_at_edge = "wrap", -- Herdr pane boundary: same
	unzoom_on_nav = true,

	-- Sidebars/pickers this config actually uses, on top of the plugin's
	-- defaults — keeps the resize keys from getting trapped inside them.
	ignored_filetypes = {
		"neo-tree",
		"snacks_dashboard",
		"snacks_picker",
		"TelescopePrompt",
		"TelescopeResults",
		"aerial",
		"trouble",
		"dbui",
		"dbout",
		"qf",
		"quickfix",
		"toggleterm",
	},

	-- Published to the shared conf; keep in sync with the keymaps below.
	nav_keys = { left = "<C-h>", down = "<C-j>", up = "<C-k>", right = "<C-l>" },
	resize_keys = { left = "<M-h>", down = "<M-j>", up = "<M-k>", right = "<M-l>" },
})

local hs = require("herdr-splits")
local map = vim.keymap.set

-- Overrides the <C-w>h/j/k/l mappings from user/keymaps.lua for this session.
map("n", "<C-h>", hs.move_cursor_left, { silent = true, desc = "Navigate left (Herdr/Neovim)" })
map("n", "<C-j>", hs.move_cursor_down, { silent = true, desc = "Navigate down (Herdr/Neovim)" })
map("n", "<C-k>", hs.move_cursor_up, { silent = true, desc = "Navigate up (Herdr/Neovim)" })
map("n", "<C-l>", hs.move_cursor_right, { silent = true, desc = "Navigate right (Herdr/Neovim)" })

map("n", "<M-h>", hs.resize_left, { silent = true, desc = "Resize left (Herdr/Neovim)" })
map("n", "<M-j>", hs.resize_down, { silent = true, desc = "Resize down (Herdr/Neovim)" })
map("n", "<M-k>", hs.resize_up, { silent = true, desc = "Resize up (Herdr/Neovim)" })
map("n", "<M-l>", hs.resize_right, { silent = true, desc = "Resize right (Herdr/Neovim)" })
