-- local null_ls = require("null-ls")
--
-- null_ls.setup({
--     sources = {
--         null_ls.builtins.diagnostics.eslint_d, -- Example: Add ESLint if needed
--         null_ls.builtins.diagnostics.sonarlint.with({
--             command = "sonarlint-ls", -- Path to SonarLint
--             args = {}, -- You may need to adjust args
--             filetypes = { "javascript", "typescript", "java", "python" }, -- Add relevant filetypes
--         }),
--     },
-- })
--
