-- ╔══════════════════════════════════════════════════════════════════════╗
-- ║  Hyprland — Kanagawa Wave — Himal (docs/THEME.md)                     ║
-- ║  Required by home-manager (modules/home-manager/desktop/hyprland.nix) ║
-- ║  Companion theming: waybar, hyprlock, fuzzel, swaync, wlogout         ║
-- ╚══════════════════════════════════════════════════════════════════════╝
--
-- Lua config format, Hyprland 0.56+. The old hyprlang (.conf) format is
-- deprecated and is removed in 0.57. Reference:
--   https://wiki.hypr.land/Configuring/Start/
--   https://github.com/hyprwm/Hyprland/blob/main/example/hyprland.lua
--
-- home-manager pulls this in with require("<abs path>"), which registers the
-- file with Hyprland's inotify watcher: saving it reloads live, no rebuild.
-- Editor completion comes from ~/.config/hypr/.luarc.json (generated by
-- home-manager, points at the stubs shipped with the Hyprland package).

-- ── palette (Kanagawa Wave, inlined) ─────────────────────────────────────
--   crystalBlue 7E9CD8 · oniViolet 957FB8 · springBlue 7FB4CA
--   carpYellow E6C384 · waveRed E46876 · peachRed FF5D62
--   sumiInk0 16161D · sumiInk3 1F1F28 · sumiInk6 54546D


-- ═══ MONITORS ════════════════════════════════════════════════════════════

hl.monitor({ output = "HDMI-A-1", mode = "1920x1080@75", position = "0x0", scale = "1" })
hl.monitor({ output = "eDP-1", disabled = true })
hl.monitor({ output = "", mode = "preferred", position = "auto", scale = "1" }) -- hotplug fallback


-- ═══ PROGRAMS ════════════════════════════════════════════════════════════

local terminal    = "kitty"
local fileManager = "dolphin"
local menu        = "fuzzel"
local screenshot  = "flameshot gui"


-- ═══ AUTOSTART ═══════════════════════════════════════════════════════════
-- systemd user services (home-manager): awww-daemon (wallpaper), swaync.
-- hyprpaper is retired. Only non-service tools start here.

hl.on("hyprland.start", function()
    hl.exec_cmd("wl-paste --watch cliphist store")
    hl.exec_cmd("waybar")
end)


-- ═══ ENVIRONMENT ═════════════════════════════════════════════════════════

hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")


-- ═══ LOOK AND FEEL ═══════════════════════════════════════════════════════

hl.config({
    general = {
        gaps_in  = 6,
        -- top tightened — waybar brings its own margin
        gaps_out = { top = 6, right = 14, bottom = 14, left = 14 },
        border_size = 3,

        -- himal sweep: crystalBlue → oniViolet → springBlue, animated by
        -- borderangle below; inactive stays borderless so focus is unmistakable
        col = {
            active_border = {
                colors = { "rgba(7e9cd8ee)", "rgba(957fb8ee)", "rgba(7fb4caee)" },
                angle  = 45,
            },
            inactive_border = "rgba(00000000)",
        },

        resize_on_border = true,
        allow_tearing    = false,

        layout = "dwindle",
    },

    decoration = {
        rounding       = 10,
        rounding_power = 3, -- squircle corners

        active_opacity   = 1.0,
        inactive_opacity = 1.0,
        dim_inactive     = true,
        dim_strength     = 0.12, -- unfocused windows visibly recede
        dim_special      = 0.25, -- dim behind the scratchpad overlay

        -- subtle vibrance — muted colors get a gentle lift (docs in the shader).
        -- Disabled: a full-screen per-pixel pass every frame costs real FPS on
        -- the Vega 7 iGPU. Uncomment to trade smoothness for the look.
        -- screen_shader = "~/nixos/dotfiles/hypr/shaders/vibrance.frag",

        shadow = {
            enabled      = true,
            range        = 18,
            render_power = 3,
            color        = "rgba(16161daa)",
        },

        blur = {
            enabled = true,
            size    = 6,
            passes  = 2,     -- 3 passes at size 8 dropped frames on the Vega 7 iGPU
            popups  = true,
            special = false, -- blurring special workspace backdrop is expensive — caused fullscreen jitter in scratchpad; dim_special still marks the overlay
            vibrancy          = 0.25,
            vibrancy_darkness = 0.3,
        },
    },

    animations = {
        enabled = true,
    },
})

-- material-expressive curves + end-4 style menu curves
hl.curve("standard",        { type = "bezier", points = { { 0.2, 0 },    { 0, 1 } } })
hl.curve("emphasizedDecel", { type = "bezier", points = { { 0.05, 0.7 }, { 0.1, 1 } } })
hl.curve("emphasizedAccel", { type = "bezier", points = { { 0.3, 0 },    { 0.8, 0.15 } } })
hl.curve("overshot",        { type = "bezier", points = { { 0.18, 0.9 }, { 0.28, 1.08 } } })
hl.curve("menuDecel",       { type = "bezier", points = { { 0.1, 1 },    { 0, 1 } } })
hl.curve("menuAccel",       { type = "bezier", points = { { 0.38, 0.04 }, { 1, 0.07 } } })

hl.animation({ leaf = "global", enabled = true, speed = 8, bezier = "standard" })
-- the gradient sweep the col.active_border above promises: on focus the
-- angle rotates once through crystalBlue → oniViolet → springBlue, then
-- stops. `loop` would repaint the border every frame forever — on the
-- Vega 7 that is a permanent tax for an effect nobody looks at.
hl.animation({ leaf = "borderangle",      enabled = true, speed = 30,  bezier = "standard",        style = "once" })
hl.animation({ leaf = "windows",          enabled = true, speed = 5,   bezier = "overshot",        style = "popin 85%" })
hl.animation({ leaf = "windowsIn",        enabled = true, speed = 5,   bezier = "overshot",        style = "popin 85%" })
hl.animation({ leaf = "windowsOut",       enabled = true, speed = 3,   bezier = "emphasizedAccel", style = "popin 90%" })
hl.animation({ leaf = "windowsMove",      enabled = true, speed = 5,   bezier = "overshot" })
hl.animation({ leaf = "border",           enabled = true, speed = 8,   bezier = "standard" })
hl.animation({ leaf = "fade",             enabled = true, speed = 3,   bezier = "standard" })
hl.animation({ leaf = "layers",           enabled = true, speed = 4,   bezier = "menuDecel",       style = "popin 90%" })
hl.animation({ leaf = "layersOut",        enabled = true, speed = 2.5, bezier = "menuAccel",       style = "fade" })
hl.animation({ leaf = "workspaces",       enabled = true, speed = 4,   bezier = "emphasizedDecel", style = "slide" })
hl.animation({ leaf = "specialWorkspace", enabled = true, speed = 4,   bezier = "emphasizedDecel", style = "slidefadevert 15%" })

hl.config({
    dwindle = {
        preserve_split = true,
    },

    master = {
        new_status = "master",
    },

    -- tabbed window groups (SUPER+T to group, SUPER+Tab to cycle) — the groupbar
    -- is the same ink-and-pigment language as the waybar workspace pills: active
    -- tab in the crystalBlue→oniViolet sweep, inactive tabs sunk into sumiInk4
    group = {
        col = {
            border_active          = { colors = { "rgba(7e9cd8ee)", "rgba(957fb8ee)" }, angle = 45 },
            border_inactive        = "rgba(2a2a37aa)",
            border_locked_active   = { colors = { "rgba(e6c384ee)", "rgba(ffa066ee)" }, angle = 45 },
            border_locked_inactive = "rgba(2a2a37aa)",
        },

        groupbar = {
            enabled           = true,
            font_family       = "Maple Mono NF",
            font_size         = 11,
            height            = 16,
            indicator_height  = 3,
            gradients         = true,
            rounding          = 6,
            gradient_rounding = 6,
            keep_upper_gap    = true,
            text_color        = "rgb(DCD7BA)",
            col = {
                active          = "rgba(7e9cd8dd)",
                inactive        = "rgba(2a2a37cc)",
                locked_active   = "rgba(e6c384dd)",
                locked_inactive = "rgba(2a2a37cc)",
            },
        },
    },

    misc = {
        font_family              = "Maple Mono NF",
        disable_hyprland_logo    = true,
        disable_splash_rendering = true,
        force_default_wallpaper  = 0,
        background_color         = "rgb(16161D)",
    },

    cursor = {
        inactive_timeout = 8,
    },

    ecosystem = {
        no_update_news = true,
    },

    xwayland = {
        force_zero_scaling = true,
    },
})


-- ═══ INPUT ═══════════════════════════════════════════════════════════════

hl.config({
    input = {
        kb_layout    = "us",
        follow_mouse = 1,
        sensitivity  = 0,

        touchpad = {
            natural_scroll = false,
        },
    },
})

-- three-finger swipe between workspaces
hl.gesture({ fingers = 3, direction = "horizontal", action = "workspace" })


-- ═══ KEYBINDINGS ═════════════════════════════════════════════════════════

local mainMod = "SUPER"

-- ── apps ──
hl.bind(mainMod .. " + Q", hl.dsp.exec_cmd(terminal))
hl.bind(mainMod .. " + N", hl.dsp.exec_cmd(screenshot))
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd(fileManager))
hl.bind(mainMod .. " + R", hl.dsp.exec_cmd(menu))

-- ── shell: notifications · wallpaper · power ──
hl.bind(mainMod .. " + B", hl.dsp.exec_cmd("swaync-client -t -sw")) -- notification center
hl.bind(mainMod .. " + SHIFT + N", hl.dsp.exec_cmd("swaync-client --close-all"))
hl.bind(mainMod .. " + W", hl.dsp.exec_cmd("wallpaper next")) -- animated wall cycle
hl.bind(mainMod .. " + SHIFT + W", hl.dsp.exec_cmd("wallpaper random"))
hl.bind(mainMod .. " + Escape", hl.dsp.exec_cmd("wlogout -b 3 --protocol layer-shell"))

-- Bikram Sambat — what is today's Bikram Sambat date? (lib/patro.nix)
hl.bind(mainMod .. " + K", hl.dsp.exec_cmd("patro notify"))

-- ukhaan — a random Nepali proverb (lib/ukhaan.tsv)
hl.bind(mainMod .. " + U", hl.dsp.exec_cmd("ukhaan notify"))

-- nietzsche — a random Nietzsche quotation (lib/nietzsche.tsv)
hl.bind(mainMod .. " + Y", hl.dsp.exec_cmd("nietzsche notify"))

-- dhyan — dhyan mode: bar folds away, gaps open into paper margins
hl.bind(mainMod .. " + Z", hl.dsp.exec_cmd("~/nixos/dotfiles/hypr/scripts/zen.sh"))

-- ── window management ──
hl.bind(mainMod .. " + C", hl.dsp.window.close())
hl.bind(mainMod .. " + SHIFT + C", hl.dsp.exec_cmd("hyprpicker -a")) -- pick a color, hex lands in clipboard
hl.bind(mainMod .. " + V", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + P", hl.dsp.window.pseudo()) -- dwindle
hl.bind(mainMod .. " + J", hl.dsp.layout("togglesplit"))
hl.bind(mainMod .. " + F", hl.dsp.window.fullscreen({ mode = "maximized" }))
hl.bind(mainMod .. " + SHIFT + F", hl.dsp.window.fullscreen({ mode = "fullscreen" }))

-- alt+tab window cycling
hl.bind("ALT + Tab", hl.dsp.window.cycle_next())
hl.bind("ALT + SHIFT + Tab", hl.dsp.window.cycle_next({ next = false }))

-- ── tabbed groups ──
hl.bind(mainMod .. " + T", hl.dsp.group.toggle())
hl.bind(mainMod .. " + Tab", hl.dsp.group.next())
hl.bind(mainMod .. " + SHIFT + Tab", hl.dsp.group.prev())
hl.bind(mainMod .. " + SHIFT + T", hl.dsp.group.lock_active({ action = "toggle" }))

-- workspace overview (Hyprspace plugin — disabled, does not build on Hyprland
-- 0.56; see modules/home-manager/desktop/hyprland.nix). When it is re-enabled,
-- the old `overview:toggle` dispatcher needs a Lua-side equivalent — plugins
-- expose theirs under hl.plugin.<namespace>.<fn> once loaded, so check
-- `hyprctl repl` for what Hyprspace actually registers before rebinding.
-- hl.bind(mainMod .. " + grave", ...)

-- ── focus ──
hl.bind(mainMod .. " + left",  hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + up",    hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + down",  hl.dsp.focus({ direction = "down" }))

-- ── move window ──
hl.bind(mainMod .. " + SHIFT + left",  hl.dsp.window.move({ direction = "left" }))
hl.bind(mainMod .. " + SHIFT + right", hl.dsp.window.move({ direction = "right" }))
hl.bind(mainMod .. " + SHIFT + up",    hl.dsp.window.move({ direction = "up" }))
hl.bind(mainMod .. " + SHIFT + down",  hl.dsp.window.move({ direction = "down" }))

-- ── workspaces ──
for i = 1, 10 do
    local key = i % 10 -- 10 maps to key 0
    hl.bind(mainMod .. " + " .. key,           hl.dsp.focus({ workspace = i }))
    hl.bind(mainMod .. " + SHIFT + " .. key,   hl.dsp.window.move({ workspace = i }))
end

-- scratchpad
hl.bind(mainMod .. " + S", hl.dsp.workspace.toggle_special("magic"))
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.window.move({ workspace = "special:magic" }))

-- scroll through workspaces
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up",   hl.dsp.focus({ workspace = "e-1" }))

-- drag to move / resize
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(),   { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

-- ── media & hardware keys ──
-- swayosd-client shows an OSD; falls back to raw wpctl/brightnessctl until
-- the rebuild that installs swayosd
local mediaOpts = { locked = true, repeating = true }
hl.bind("XF86AudioRaiseVolume",  hl.dsp.exec_cmd("swayosd-client --output-volume raise || wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+"), mediaOpts)
hl.bind("XF86AudioLowerVolume",  hl.dsp.exec_cmd("swayosd-client --output-volume lower || wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"), mediaOpts)
hl.bind("XF86AudioMute",         hl.dsp.exec_cmd("swayosd-client --output-volume mute-toggle || wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), mediaOpts)
hl.bind("XF86AudioMicMute",      hl.dsp.exec_cmd("swayosd-client --input-volume mute-toggle || wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"), mediaOpts)
hl.bind("XF86MonBrightnessUp",   hl.dsp.exec_cmd("swayosd-client --brightness raise || brightnessctl s 10%+"), mediaOpts)
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("swayosd-client --brightness lower || brightnessctl s 10%-"), mediaOpts)

hl.bind("XF86AudioNext",  hl.dsp.exec_cmd("playerctl next"),       { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay",  hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev",  hl.dsp.exec_cmd("playerctl previous"),   { locked = true })


-- ── resize submap ────────────────────────────────────────────────────────
-- SUPER+X enters it; waybar's hyprland/submap module paints a gold pill in the
-- left island so the mode is never invisible. Escape/Return leave.
-- Unlike the old .conf format, submap membership is lexical: only binds inside
-- the hl.define_submap callback belong to it, so ordering no longer matters.

hl.bind(mainMod .. " + X", hl.dsp.submap("resize"))

hl.define_submap("resize", function()
    local step = { repeating = true }
    hl.bind("left",  hl.dsp.window.resize({ x = -40, y = 0, relative = true }), step)
    hl.bind("right", hl.dsp.window.resize({ x = 40,  y = 0, relative = true }), step)
    hl.bind("up",    hl.dsp.window.resize({ x = 0,  y = -40, relative = true }), step)
    hl.bind("down",  hl.dsp.window.resize({ x = 0,  y = 40,  relative = true }), step)
    hl.bind("h", hl.dsp.window.resize({ x = -40, y = 0, relative = true }), step)
    hl.bind("l", hl.dsp.window.resize({ x = 40,  y = 0, relative = true }), step)
    hl.bind("k", hl.dsp.window.resize({ x = 0,  y = -40, relative = true }), step)
    hl.bind("j", hl.dsp.window.resize({ x = 0,  y = 40,  relative = true }), step)

    hl.bind("escape", hl.dsp.submap("reset"))
    hl.bind("Return", hl.dsp.submap("reset"))
end)


-- ═══ WORKSPACE RULES ═════════════════════════════════════════════════════

-- scratchpad inherits regular gaps — dim_special marks it as an overlay


-- ═══ WINDOW RULES ════════════════════════════════════════════════════════

-- ignore maximize requests from apps
hl.window_rule({
    name  = "suppress-maximize-events",
    match = { class = ".*" },

    suppress_event = "maximize",
})

-- fix some dragging issues with XWayland
hl.window_rule({
    name  = "fix-xwayland-drags",
    match = {
        class      = "^$",
        title      = "^$",
        xwayland   = true,
        float      = true,
        fullscreen = false,
        pin        = false,
    },

    no_focus = true,
})

-- warn red border while maximized (fullscreen mode 1); normal borders
-- restore automatically on exit — a match.fullscreen = false rule would paint
-- EVERY non-fullscreen window with the active gradient, killing focus contrast
hl.window_rule({
    name  = "maximized-warn-border",
    match = { fullscreen = true },

    border_color = { colors = { "rgba(ff5d62ee)", "rgba(e46876ee)" }, angle = 45 },
})

-- floating windows wear the violet half of the sweep, so "is this tiled?" is
-- answerable from the border alone. Safe where a fullscreen = false match
-- isn't: match.float selects only floats, not every ordinary window.
hl.window_rule({
    name  = "float-border",
    match = { float = true },

    border_color = { colors = { "rgba(957fb8ee)", "rgba(7fb4caee)" }, angle = 45 },
})

-- flameshot v14 on Hyprland — without these, the overlay positions/sizes wrong
hl.window_rule({
    name  = "flameshot",
    match = { class = "flameshot" },

    float   = true,
    pin     = true,
    no_anim = true,
    move    = { 0, 0 },
})

-- system TUIs launched from waybar (btop, nmtui, bluetoothctl, docker stats)
hl.window_rule({
    name  = "waybar-tui-popup",
    match = { class = "waybar-tui" },

    float  = true,
    size   = { 1100, 680 },
    center = true,
})

-- audio mixer as a floating panel
hl.window_rule({
    name  = "float-audio-mixer",
    match = { class = "(org.pulseaudio.pavucontrol|pavucontrol)" },

    float  = true,
    size   = { 900, 620 },
    center = true,
})

-- picture-in-picture: pinned, bottom-right, always on top
hl.window_rule({
    name  = "pip",
    match = { title = "^(Picture-in-Picture)$" },

    float             = true,
    pin               = true,
    keep_aspect_ratio = true,
    size              = { 480, 270 },
    move              = { "100%-500", "100%-310" },
})

-- file pickers and dialogs float centered
hl.window_rule({
    name  = "float-dialogs",
    match = { title = "^(Open File|Save File|Open Folder|Select Folder|File Upload)(.*)$" },

    float  = true,
    size   = { "60%", "65%" },
    center = true,
})

-- keep the screen awake while anything runs fullscreen (video calls, players)
hl.window_rule({
    name  = "fullscreen-idle-inhibit",
    match = { class = ".*" },

    idle_inhibit = "fullscreen",
})

-- terminal depth: unfocused terminals go faintly translucent (compositor
-- blur fills in behind) — pairs with dim_inactive for a layered ink look
hl.window_rule({
    name  = "terminal-depth",
    match = { class = "(kitty|com.mitchellh.ghostty|org.wezfurlong.wezterm)" },

    opacity = "1.0 0.94",
})


-- ═══ PLUGINS ═════════════════════════════════════════════════════════════
-- Loaded by home-manager, which emits hl.plugin.load(...) above this file's
-- require(). Plugin config values only exist after the plugin is dlopen'd,
-- which happens after the first config pass — so the get_config guard keeps
-- the first pass (and any run with the plugin missing) free of errors.
--
-- The overview block below belongs to hyprspace, which is disabled while it
-- lacks Hyprland 0.56 support. Kept commented so re-enabling is one uncomment
-- here plus one in modules/home-manager/desktop/hyprland.nix.

-- if hl.get_config("plugin.overview.panelColor") ~= nil then
--     hl.config({
--         plugin = {
--             overview = {
--                 panelColor              = "rgba(1f1f28cc)",
--                 panelBorderColor        = "rgba(54546d88)",
--                 workspaceActiveBorder   = "rgba(7e9cd8ee)",
--                 workspaceInactiveBorder = "rgba(36364655)",
--                 panelBorderWidth        = 2,
--                 gapsIn                  = 6,
--                 gapsOut                 = 12,
--                 exitOnClick             = true,
--                 switchOnDrop            = true,
--                 centerAligned           = true,
--                 showNewWorkspace        = true,
--             },
--         },
--     })
-- end

-- hyphens in a plugin's config namespace become underscores in Lua:
-- plugin:dynamic-cursors:mode  →  plugin.dynamic_cursors.mode
if hl.get_config("plugin.dynamic_cursors.enabled") ~= nil then
    hl.config({
        plugin = {
            dynamic_cursors = {
                enabled   = true,
                mode      = "tilt", -- cursor leans into acceleration
                threshold = 2,

                -- shaking the cursor magnifies it; the magnification itself
                -- has no on/off switch, it *is* what shake does. Size comes
                -- from base + speed * shake-intensity, clamped by limit
                -- (0 = uncapped).
                shake = {
                    enabled   = true,
                    threshold = 6.0,  -- shake intensity needed to trigger
                    base      = 4.0,  -- magnification at trigger
                    speed     = 4.0,  -- extra magnification per intensity
                    timeout   = 2000, -- ms of stillness before it shrinks back
                },
            },
        },
    })
end


-- ═══ LAYER RULES ═════════════════════════════════════════════════════════
-- frosted glass for the shell: waybar islands, fuzzel, swaync, swayosd, wlogout
--
-- `xray = true` makes a layer's blur sample the wallpaper only, skipping every
-- window underneath. It is both cheaper (one static texture instead of the
-- live window stack, re-blurred per frame as those windows repaint) and
-- calmer to look at — the bar stops strobing when a terminal scrolls behind
-- it. The shell reads as glass over paper, not glass over chaos.

hl.layer_rule({
    name  = "blur-waybar",
    match = { namespace = "waybar" },

    blur         = true,
    ignore_alpha = 0.29,
    xray         = true,
})

hl.layer_rule({
    name  = "blur-launcher",
    match = { namespace = "launcher" },

    blur         = true,
    ignore_alpha = 0.29,
    xray         = true,
})

hl.layer_rule({
    name  = "blur-swaync-notifications",
    match = { namespace = "swaync-notification-window" },

    blur         = true,
    ignore_alpha = 0.29,
})

hl.layer_rule({
    name  = "blur-swaync-control-center",
    match = { namespace = "swaync-control-center" },

    blur         = true,
    ignore_alpha = 0.29,
})

hl.layer_rule({
    name  = "blur-swayosd",
    match = { namespace = "swayosd" },

    blur         = true,
    ignore_alpha = 0.29,
    xray         = true,
})

hl.layer_rule({
    name  = "blur-wlogout",
    match = { namespace = "logout_dialog" },

    blur = true,
})
