require("mini.pairs").setup({})
require("mini.surround").setup({})
require("mini.map").setup({})
require("mini.indentscope").setup({})
require("mini.cursorword").setup({})
require("mini.ai").setup({})
