-- local config = {
--   cmd = {
--     'java', -- Ensure this points to your Java 17 or newer binary
--
--     '-Declipse.application=org.eclipse.jdt.ls.core.id1',
--     '-Dosgi.bundles.defaultStartLevel=4',
--     '-Declipse.product=org.eclipse.jdt.ls.core.product',
--     '-Dlog.protocol=true',
--     '-Dlog.level=ALL',
--     '-Xmx1g',
--     '--add-modules=ALL-SYSTEM',
--     '--add-opens', 'java.base/java.util=ALL-UNNAMED',
--     '--add-opens', 'java.base/java.lang=ALL-UNNAMED',
--
--     '-jar', '/nix/store/301k2jhjanl6rr96b9yy9qzcrhjbwgmz-jdt-language-server-1.36.0/share/java/jdtls/plugins/org.eclipse.equinox.launcher_1.6.800.v20240513-1750.jar',
--
--     '-configuration', '/nix/store/301k2jhjanl6rr96b9yy9qzcrhjbwgmz-jdt-language-server-1.36.0/share/java/jdtls/config_linux',
--
--     '-data', '/home/hubert/IdeaProjects/web/influx-mca-web'
--   },
--
--   root_dir = require('jdtls.setup').find_root({'.git', 'mvnw', 'gradlew'}),
--
--   settings = {
--     java = {}
--   },
--
--   init_options = {
--     bundles = {}
--   },
-- }
--
-- require('jdtls').start_or_attach(config)
--
