# Herdr — terminal workspace manager / agent multiplexer (https://herdr.dev)
#
# The herdr-splits integration has two halves that MUST come from the same
# release, or the generated conf and the scripts reading it drift apart:
#
#   1. Herdr side  — herdr-plugin.toml + scripts/herdr-{nav,resize}.sh, which
#                    expose the `herdr-splits.nav-*` / `resize-*` plugin actions
#                    bound in config.toml below.
#   2. Neovim side — lua/herdr-splits/*, wired in packages/neovim/plugins.nix
#                    and configured by nvim/lua/user/herdr-splits.lua.
#
# Both halves live in ONE derivation: pkgs.vimPlugins.herdr-splits-nvim is a
# plain copy of the upstream repo, so it ships the herdr-side manifest and
# shell scripts alongside the Lua. That is why this module reaches into
# vimPlugins rather than looking for a separate herdr-plugin package.
{
  config,
  lib,
  pkgs,
  ...
}: let
  cfg = config.modules.programs.herdr;

  # Same derivation the Neovim side loads — see packages/neovim/plugins.nix.
  herdrSplits = pkgs.vimPlugins.herdr-splits-nvim;
in {
  options.modules.programs.herdr = {
    enable = lib.mkEnableOption "Herdr terminal agent multiplexer";

    enableSplits = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = ''
        Wire up herdr-splits: seamless ctrl+h/j/k/l navigation and
        alt+h/j/k/l resizing across Herdr panes and Neovim splits.
      '';
    };
  };

  config = lib.mkIf cfg.enable (lib.mkMerge [
    {
      home.packages = [pkgs.herdr];
    }

    (lib.mkIf cfg.enableSplits {
      # Herdr's plugin registry is mutable state (~/.config/herdr/plugins.json,
      # written by `herdr plugin install/link/enable`), so it can't be a
      # read-only symlink — other plugins installed by hand must survive.
      # Re-linking is idempotent: it replaces the herdr-splits entry in place
      # rather than appending, which also repoints plugin_root at the new store
      # path whenever nixpkgs bumps the plugin.
      home.activation.herdrSplitsLink = lib.hm.dag.entryAfter ["writeBoundary"] ''
        ${pkgs.herdr}/bin/herdr plugin link ${herdrSplits} >/dev/null 2>&1 || \
          echo "warning: failed to link herdr-splits plugin into herdr" >&2
      '';

      # config.toml is fully declarative here. `herdr config reset-keys` and
      # any other command that rewrites this file will fail against the
      # read-only symlink — change keybindings in this module instead, or set
      # HERDR_CONFIG_PATH to escape to a mutable copy.
      #
      # The nav-*/resize-* actions decide per keypress whether the focused pane
      # is running Neovim: if it is, the chord is forwarded into Neovim (which
      # owns in-split movement and edge crossing); if not, Herdr moves pane
      # focus itself. The chords below must match nav_keys/resize_keys in
      # nvim/lua/user/herdr-splits.lua.
      xdg.configFile."herdr/config.toml".text = ''
        # Generated by modules/home-manager/programs/herdr.nix — do not edit.
        # `herdr --default-config` prints every available option.

        [keys]

        # ── herdr-splits: navigation (Herdr panes ↔ Neovim splits) ──
        [[keys.command]]
        key = "ctrl+h"
        type = "plugin_action"
        command = "herdr-splits.nav-left"

        [[keys.command]]
        key = "ctrl+j"
        type = "plugin_action"
        command = "herdr-splits.nav-down"

        [[keys.command]]
        key = "ctrl+k"
        type = "plugin_action"
        command = "herdr-splits.nav-up"

        [[keys.command]]
        key = "ctrl+l"
        type = "plugin_action"
        command = "herdr-splits.nav-right"

        # ── herdr-splits: resizing ──
        [[keys.command]]
        key = "alt+h"
        type = "plugin_action"
        command = "herdr-splits.resize-left"

        [[keys.command]]
        key = "alt+j"
        type = "plugin_action"
        command = "herdr-splits.resize-down"

        [[keys.command]]
        key = "alt+k"
        type = "plugin_action"
        command = "herdr-splits.resize-up"

        [[keys.command]]
        key = "alt+l"
        type = "plugin_action"
        command = "herdr-splits.resize-right"
      '';
    })
  ]);
}
