# Home machine hardware configuration
# Generated by 'nixos-generate-config'
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/171c3e75-1b84-4914-840b-bd8bccf3ad1a";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/1239-E7C2";
    fsType = "vfat";
    options = [ "fmask=0077" "dmask=0077" ];
  };

  fileSystems."/nix/store" = {
    device = "/dev/disk/by-uuid/9c498fa9-290c-44ef-914f-aa0987369009";
    fsType = "ext4";
    options = [ "defaults" ];
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/847210ca-919a-48f0-b4a5-36e87fdb38ca"; }
  ];

  networking.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
